print("Type something and wait...")
x = input("? ")
print(f"You typed: {x}")
print("Type something and wait...")
x = input("? ")
print(f"You typed: {x}")
print("Type something and wait...")
x = input("? ")
print(f"You typed: {x}")